# Generated by Django 4.0.4 on 2023-01-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_purchase_voucher_receipt_purchase_voucher_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_itemcreation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='under',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
