# Generated by Django 4.0.4 on 2023-01-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_purchasevoucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher'),
        ),
    ]
