# Generated by Django 4.0.4 on 2023-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_purchasevoucher_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
